# Generated by Django 4.2.29 on 2026-05-06 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_responsableprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
